### ISSUE TITLE
Support multiple clusters kubernetes

### ISSUE THREAD

**Issue by jhonmike** [dash-ops/dash-ops#13]
## Requirements:

Make features available to more than one cluster by reading settings from context.

### Example config:

```yaml
kubernetes:
  - name: 'Kubernetes Dev'
    kubeconfig: ~/.kube/config
    context: 'sandbox'
  - name: 'Kubernetes Prod'
    kubeconfig: ~/.kube/config
    context: 'prod'
```
