### ISSUE TITLE
Support multiple aws accounts

### ISSUE THREAD

**Issue by jhonmike** [dash-ops/dash-ops#19]
## Requirements:

Make features available to more than one account by reading settings from aws account name.

### Example config:

```yaml
aws:
  - name: 'AWS Dev'
    region_default: us-east-1
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
 - name: 'AWS Prod'
    region_default: us-east-1
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
```
